### ISSUE TITLE
Upload datasets used in solving the practice

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#110]
@abrilr1604, can you upload to [this folder](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Projects/Data%20Lab/Alternative%20Data%20for%20Crisis/datasets_solved_practice?csf=1&web=1&e=XxrRqv) the datasets you used for solving the practices you had done so far?

**Comment by abrilr1604** [comment]
@msoltadeo done!

**Comment by msoltadeo** [comment]
Thank you :rocket:
