### ISSUE TITLE
Global Course - Crisis | Create notebooks for Mapping and Monitoring Floods 

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#13]
Hands-on guidance will be provided on how to access and use NASA’s [MODIS Near Real Time Global Flood Product](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fwww.earthdata.nasa.gov.mcas.ms%2Flearn%2Ffind-data%2Fnear-real-time%2Fmodis-nrt-global-flood-product%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1), a daily, near-global, ~250 m resolution product showing flood and surface water detected from the twice-daily overpass of the MODIS satellite optical sensors. The data can be quickly explored on [a Google Earth Engine application](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fkmarkert.users.earthengine.app.mcas.ms%2Fview%2Fmodis-flood-app%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1),  general information on the most recent global flood activity can be found on the [UN International Charter for Natural Disasters site](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fdisasterscharter.org.mcas.ms%2Fweb%2Fguest%2Fhome%3Bjsessionid%3D6D0927B631ACE1F1EE4C4DE6654D98A1.APP1%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1).

**Comment by msoltadeo** [comment]
[This](https://github.com/datapartnership/alternative-data-for-crisis/blob/mapping_monitoring_floods/notebooks/mapping_monitoring_floods.ipynb) is the notebook I was working with. I started it when the Brazil flood occured, so, I was able to get the data. Then, I tried to download the data for Lybia's flood but was not able to find where to download past images.

**Comment by g4brielvs** [comment]
I also haven't been able to retrieve the historical data from NASA’s [MODIS Near Real Time Global Flood Product](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fwww.earthdata.nasa.gov.mcas.ms%2Flearn%2Ffind-data%2Fnear-real-time%2Fmodis-nrt-global-flood-product%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1).

**Comment by msoltadeo** [comment]
@g4brielvs this is what the documentation says:
![image](https://github.com/user-attachments/assets/de1d7b52-b279-4016-bacf-948c5cc50b07)
Somehow, I got into [this tutorial](https://nasa-gibs.github.io/gibs-api-docs/python-usage/) and thought that there might be a way to get the data here. But I am not completely sure if this is the right way to go. 
I attach here the notebook I was working with. 

[access_flood_data.zip](https://github.com/user-attachments/files/16603528/access_flood_data.zip)

**Comment by msoltadeo** [comment]
@g4brielvs , I spole with Holly and we are going to use the data for Brasil flood. I will finish the notebook I already started.

**Comment by msoltadeo** [comment]
Closing this for now. In the future, it will be nice to create a notbook for downloading and using [this data](https://nasa-gibs.github.io/gibs-api-docs/python-usage/)
