### ISSUE TITLE
Estimating Physical Impact - Internet Connectivity

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#18]
Internet Connectivity 

Project Reference: [Turkiye Earthquake Internet Connectivity](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fdatapartnership.org.mcas.ms%2Fturkiye-earthquake-impact%2Fnotebooks%2Finternet-connectivity%2FREADME.html%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1)

**Comment by msoltadeo** [comment]
Created the notenook in [this](https://github.com/datapartnership/alternative-data-for-crisis/tree/internet_conectivity) branch. But I cannot find the data for Ookla.

@SahitiSarva , where can I find the raw data for recreating [the original notebook](https://github.com/datapartnership/turkiye-earthquake-impact/blob/main/notebooks/internet-connectivity/03b-ookla-speedtest-analysis.ipynb)?

**Comment by SahitiSarva** [comment]
@msoltadeo it's on [SharePoint](https://worldbankgroup.sharepoint.com/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FProjects%2FData%20Lab%2FTurkiye%20Earthquake%20Impact%2FData%2Fookla%5Fspeedtest&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5)

**Comment by msoltadeo** [comment]
PR #42

**Comment by msoltadeo** [comment]
The Ookla part is still incomplete
