### ISSUE TITLE
Estimating Disruption to Business and Trade - Business Activity Trends 

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#22]
Using the Meta Business Activity Trends dataset, analyze posting patterns of SMEs through the course of a crisis.  

 

Project Reference: [Turkiye Earthquake Business Activity Trends](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fdatapartnership.org.mcas.ms%2Fturkiye-earthquake-impact%2Fnotebooks%2Fbusiness-activity-trends%2FREADME.html%3FMcasTsid%3D15600&McasCSRF=c3215e4e2725edb8242b3e295430bd8b250649cd91bbdefb75b7eeb4bd3f7af1)

**Comment by msoltadeo** [comment]
@SahitiSarva , do you have the raw data for recreating [this notebook](https://github.com/datapartnership/turkiye-earthquake-impact/blob/main/notebooks/business-activity-trends/01-business-activity-trends.ipynb). If not, which of these files in [this notebok](https://github.com/datapartnership/turkiye-earthquake-impact/blob/main/notebooks/business-activity-trends/01-business-activity-trends.ipynb) should I use? Also, I was reviewing some of those files and found that they have a `ds` and a `date` column that store different values. What is the relation between those columns, do you know?

**Comment by msoltadeo** [comment]
PR #41

**Comment by SahitiSarva** [comment]
@msoltadeo -- did you already fix this?

**Comment by msoltadeo** [comment]
@SahitiSarva , I think I solved it. I am using the file named `business_activity_trends_raw.csv` is that OK?

**Comment by SahitiSarva** [comment]
Yes
