### ISSUE TITLE
GitHub Step by Step guide

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#33]
It is common among newly data scientist to not know how to work with GitHub. As the course will be available through a GitHub repository, we will provide a step by step guide on how to clone a GitHub repository so they can get the material.

Add the option to do this in Google Colab since several students will be working there.

**Comment by g4brielvs** [comment]
Allow me to offer a suggestion: proficiency in Git/GitHub should be considered a prerequisite. There are numerous excellent resources available, including:

- [Git Guides](https://github.com/git-guides)
- [Getting Started with GitHub Desktop](https://docs.github.com/en/desktop/overview/getting-started-with-github-desktop)
- [World Bank Data Good Training: Contributing](https://worldbank.github.io/data-good-training/docs/CONTRIBUTING.html)

**Comment by msoltadeo** [comment]
@g4brielvs, these resources are great :smile: Thank you for sharing them. We can definetely use them.
