### ISSUE TITLE
Map with timeslider

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#36]
@g4brielvs I wanted to show radiance at each administrative boundary 2 across the time. So, wanted a folium map with a timeslider. I [created it](https://github.com/datapartnership/alternative-data-for-crisis/blob/night_time_lights/notebooks/NTL.ipynb) but it is not working. I think that it might be related to the fact that I have MultiPolygons instead of Polygons.

**Comment by msoltadeo** [comment]
I found ot how to do it.

**Comment by g4brielvs** [comment]
@msoltadeo Unfortunately, it doesn't seem that the timeslider will work on Jupyter Book. We might have to add some JS dependencies (which is possible). I'll investigate further.

**Comment by msoltadeo** [comment]
@g4brielvs, I found how to do it. Do not worry about it :)
