### ISSUE TITLE
Global Course - Crisis | Review mapping-and-monitoring-earthquake-intensity

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#77]
@abrilr1604 Similar to what you did for #73 

- [ ] Review the class as if you were a student from [here](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-and-monitoring-extent/mapping-and-monitoring-earthquake-intensity.html). You do not need to understand/review the whole code. 
- [ ] Download the data using the information from the notebook.
- [ ] Run the notebook and check that everything is running smoothly.
- [ ] The data is also stored [here](https://worldbankgroup.sharepoint.com/:f:/t/DevelopmentDataPartnershipCommunity-WBGroup/EktlWsKcMCtCopL20xDZFoEBoEW1JD5CBe3BXIpbk-W1NQ?email=arodriguez12%40worldbank.org&e=F90hRI). This is a back-up in case the day of the course the link for downloading is not working. Please check that the notebook also runs with this data.
- [ ] Do the practice and provide feedback. Was it difficult? Was it useful to understand the concepts? 
- [ ] Create a list of suggestions if needed. For example, parts you did not understand, parts that could be improved

**Comment by abrilr1604** [comment]
@msoltadeo

- the code runs perfectly. 
- everything is clear and understandable.
- I created a pull request with the notebook for the practice solution, and I also fixed some typos in other notebooks. Please review the solution notebook to ensure I’ve solved it correctly 🙂

**Comment by msoltadeo** [comment]
@abrilr1604 Thank you! :rocket:
