### ISSUE TITLE
Global Course - Crisis | Review mapping-and-monitoring-surface-change

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#80]
@abrilr1604 similar to what you did for #73 
- [ ] Review the class as if you were a student from [here](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-and-monitoring-extent/mapping-and-monitoring-surface-change.html). There is nothing to run here as it is a demo class. 
- [ ] Create a list of suggestions if needed. For example, parts you did not understand, parts that could be improved

**Comment by abrilr1604** [comment]
@msoltadeo I read this on friday and found it very useful and understandable! I only added some missing periods which you can see in the PR 😁

**Comment by msoltadeo** [comment]
@abrilr1604 thank you :muscle:
